export const Categories = [
  { path: "co-trang", title: "Cổ Trang" },
  { path: "tam-ly", title: "Tâm Lý" },
  { path: "tinh-cam", title: "Tình Cảm" },
  { path: "bi-an", title: "Bí Ẩn" },
  { path: "kinh-di", title: "Kinh Dị" },
  { path: "hanh-dong", title: "Hành Động" },
  { path: "vo-thuat", title: "Võ Thuật" },
  { path: "kich-tinh", title: "Kịch Tính" },
  { path: "chien-tranh", title: "Chiến Tranh" },
  { path: "phieu-luu", title: "Phiêu Lưu" },
  { path: "hai", title: "Hài" },
  { path: "hinh-su", title: "Hình Sự" },
  { path: "gia-dinh", title: "Gia Đình" },
  { path: "khoa-hoc", title: "Khoa Học" },
  { path: "am-nhac", title: "Âm Nhạc" },
  { path: "vien-tuong", title: "Viễn Tưởng" },
  { path: "than-loai", title: "Thần Loại" },
  { path: "chinh-kich", title: "Chính Kịch" },
  { path: "tv-shows", title: "TV Shows" },
  { path: "hoat-hinh", title: "Hoạt Hình" },
  { path: "tai-lieu", title: "Tài Liệu" },
  { path: "thieu-nhi", title: "Thiếu Nhi" },
  { path: "lang-man", title: "Lãng Mạn" }, // Added category
  { path: "khoa-hoc-vien-tuong", title: "Khoa Học VT" }, // Added category
  { path: "huyen-bi", title: "Huyền Bí" }, // Added category
  { path: "nhac-kich", title: "Nhạc Kịch" }, // Added category
  { path: "mien-tay", title: "Miền Tây" }, // Added category
  { path: "lich-su", title: "Lịch Sử" }, // Added category
  { path: "toi-pham", title: "Tội Phạm" }, // Added category
  { path: "huyen-bi", title: "Huyền Bí" }, // Added category
  { path: "phieu-luu", title: "Phiêu Lưu" }, // Added category
  { path: "chien-tranh", title: "Chiến Tranh" }, // Added category
  { path: "the-thao", title: "Thể Thao" }, // Added category
  { path: "tieu-su", title: "Tiểu Sử" }, // Added category
  { path: "tai-lieu-kich", title: "Tài Liệu Kịch" }, // Added category
  { path: "gia-dinh", title: "Gia Đình" }, // Added category
  { path: "giat-gan", title: "Giật Gân" }, // Added category
  { path: "thi-nghiem", title: "Thí Nghiệm" }, // Added category
  { path: "18", title: "18+" }, // Added category
]
export const listFilmsOp = [
  { path: "/danh-sach/phim-le", title: "Phim Lẻ" },
  { path: "/danh-sach/phim-bo", title: "Phim Bộ" },
  { path: "/danh-sach/hoat-hinh", title: "Phim Hoạt Hình" },
  { path: "/danh-sach/TV-Shows", title: "TV Shows" },
]
export const ListYear = [
  { path: "/danh-sach/phim-theo-nam?year=2026", title: "2026" },
  { path: "/danh-sach/phim-theo-nam?year=2025", title: "2025" },
  { path: "/danh-sach/phim-theo-nam?year=2024", title: "2024" },
  { path: "/danh-sach/phim-theo-nam?year=2023", title: "2023" },
  { path: "/danh-sach/phim-theo-nam?year=2022", title: "2022" },
  { path: "/danh-sach/phim-theo-nam?year=2021", title: "2021" },
  { path: "/danh-sach/phim-theo-nam?year=2020", title: "2020" },
  { path: "/danh-sach/phim-theo-nam?year=2019", title: "2019" },
  { path: "/danh-sach/phim-theo-nam?year=2018", title: "2018" },
  { path: "/danh-sach/phim-theo-nam?year=2017", title: "2017" },
  { path: "/danh-sach/phim-theo-nam?year=2016", title: "2016" },
  { path: "/danh-sach/phim-theo-nam?year=2015", title: "2015" },
  { path: "/danh-sach/phim-theo-nam?year=2014", title: "2014" },
  { path: "/danh-sach/phim-theo-nam?year=2013", title: "2013" },
  { path: "/danh-sach/phim-theo-nam?year=2012", title: "2012" },
  { path: "/danh-sach/phim-theo-nam?year=2011", title: "2011" },
  { path: "/danh-sach/phim-theo-nam?year=2010", title: "2010" },
  { path: "/danh-sach/phim-theo-nam?year=2009", title: "2009" },
  { path: "/danh-sach/phim-theo-nam?year=2008", title: "2008" },
  { path: "/danh-sach/phim-theo-nam?year=2007", title: "2007" },
  { path: "/danh-sach/phim-theo-nam?year=2006", title: "2006" },
  { path: "/danh-sach/phim-theo-nam?year=2005", title: "2005" },
  { path: "/danh-sach/phim-theo-nam?year=2004", title: "2004" },
  { path: "/danh-sach/phim-theo-nam?year=2003", title: "2003" },
  { path: "/danh-sach/phim-theo-nam?year=2002", title: "2002" },
  { path: "/danh-sach/phim-theo-nam?year=2001", title: "2001" },
  { path: "/danh-sach/phim-theo-nam?year=2000", title: "2000" },
  { path: "/danh-sach/phim-theo-nam?year=1999", title: "1999" },
  { path: "/danh-sach/phim-theo-nam?year=1998", title: "1998" },
  { path: "/danh-sach/phim-theo-nam?year=1997", title: "1997" },
  { path: "/danh-sach/phim-theo-nam?year=1996", title: "1996" },
  { path: "/danh-sach/phim-theo-nam?year=1995", title: "1995" },
  { path: "/danh-sach/phim-theo-nam?year=1994", title: "1994" },
  { path: "/danh-sach/phim-theo-nam?year=1993", title: "1993" },
  { path: "/danh-sach/phim-theo-nam?year=1992", title: "1992" },
  { path: "/danh-sach/phim-theo-nam?year=1991", title: "1991" },
  { path: "/danh-sach/phim-theo-nam?year=1990", title: "1990" },
  { path: "/danh-sach/phim-theo-nam?year=1989", title: "1989" },
  { path: "/danh-sach/phim-theo-nam?year=1988", title: "1988" },
  { path: "/danh-sach/phim-theo-nam?year=1987", title: "1987" },
  { path: "/danh-sach/phim-theo-nam?year=1986", title: "1986" },
  { path: "/danh-sach/phim-theo-nam?year=1985", title: "1985" },
  { path: "/danh-sach/phim-theo-nam?year=1984", title: "1984" },
  { path: "/danh-sach/phim-theo-nam?year=1983", title: "1983" },
  { path: "/danh-sach/phim-theo-nam?year=1982", title: "1982" },
  { path: "/danh-sach/phim-theo-nam?year=1981", title: "1981" },
  { path: "/danh-sach/phim-theo-nam?year=1980", title: "1980" },
  { path: "/danh-sach/phim-theo-nam?year=1979", title: "1979" },
  { path: "/danh-sach/phim-theo-nam?year=1978", title: "1978" },
  { path: "/danh-sach/phim-theo-nam?year=1977", title: "1977" },
  { path: "/danh-sach/phim-theo-nam?year=1976", title: "1976" },
  { path: "/danh-sach/phim-theo-nam?year=1975", title: "1975" },
  { path: "/danh-sach/phim-theo-nam?year=1974", title: "1974" },
  { path: "/danh-sach/phim-theo-nam?year=1973", title: "1973" },
  { path: "/danh-sach/phim-theo-nam?year=1972", title: "1972" },
  { path: "/danh-sach/phim-theo-nam?year=1971", title: "1971" },
  { path: "/danh-sach/phim-theo-nam?year=1970", title: "1970" },
  { path: "/danh-sach/phim-theo-nam?year=1969", title: "1969" },
  { path: "/danh-sach/phim-theo-nam?year=1968", title: "1968" },
  { path: "/danh-sach/phim-theo-nam?year=1967", title: "1967" },
  { path: "/danh-sach/phim-theo-nam?year=1966", title: "1966" },
  { path: "/danh-sach/phim-theo-nam?year=1965", title: "1965" },
  { path: "/danh-sach/phim-theo-nam?year=1964", title: "1964" },
  { path: "/danh-sach/phim-theo-nam?year=1963", title: "1963" },
  { path: "/danh-sach/phim-theo-nam?year=1962", title: "1962" },
  { path: "/danh-sach/phim-theo-nam?year=1961", title: "1961" },
  { path: "/danh-sach/phim-theo-nam?year=1960", title: "1960" },
  { path: "/danh-sach/phim-theo-nam?year=1959", title: "1959" },
  { path: "/danh-sach/phim-theo-nam?year=1958", title: "1958" },
  { path: "/danh-sach/phim-theo-nam?year=1957", title: "1957" },
  { path: "/danh-sach/phim-theo-nam?year=1956", title: "1956" },
  { path: "/danh-sach/phim-theo-nam?year=1955", title: "1955" },
  { path: "/danh-sach/phim-theo-nam?year=1954", title: "1954" },
  { path: "/danh-sach/phim-theo-nam?year=1953", title: "1953" },
  { path: "/danh-sach/phim-theo-nam?year=1952", title: "1952" },
  { path: "/danh-sach/phim-theo-nam?year=1951", title: "1951" },
  { path: "/danh-sach/phim-theo-nam?year=1950", title: "1950" },
  { path: "/danh-sach/phim-theo-nam?year=1949", title: "1949" },
  { path: "/danh-sach/phim-theo-nam?year=1948", title: "1948" },
  { path: "/danh-sach/phim-theo-nam?year=1947", title: "1947" },
  { path: "/danh-sach/phim-theo-nam?year=1946", title: "1946" },
  { path: "/danh-sach/phim-theo-nam?year=1945", title: "1945" },
  { path: "/danh-sach/phim-theo-nam?year=1944", title: "1944" },
  { path: "/danh-sach/phim-theo-nam?year=1943", title: "1943" },
  { path: "/danh-sach/phim-theo-nam?year=1942", title: "1942" },
  { path: "/danh-sach/phim-theo-nam?year=1941", title: "1941" },
  { path: "/danh-sach/phim-theo-nam?year=1940", title: "1940" },
  { path: "/danh-sach/phim-theo-nam?year=1939", title: "1939" },
  { path: "/danh-sach/phim-theo-nam?year=1938", title: "1938" },
  { path: "/danh-sach/phim-theo-nam?year=1937", title: "1937" },
  { path: "/danh-sach/phim-theo-nam?year=1936", title: "1936" },
  { path: "/danh-sach/phim-theo-nam?year=1935", title: "1935" },
  { path: "/danh-sach/phim-theo-nam?year=1934", title: "1934" },
  { path: "/danh-sach/phim-theo-nam?year=1933", title: "1933" },
  { path: "/danh-sach/phim-theo-nam?year=1932", title: "1932" },
  { path: "/danh-sach/phim-theo-nam?year=1931", title: "1931" },
  { path: "/danh-sach/phim-theo-nam?year=1930", title: "1930" },
  { path: "/danh-sach/phim-theo-nam?year=1929", title: "1929" },
  { path: "/danh-sach/phim-theo-nam?year=1928", title: "1928" },
  { path: "/danh-sach/phim-theo-nam?year=1927", title: "1927" },
]
export const nationals = [
  { path: "au-my", title: "Âu Mỹ" },
  { path: "han-quoc", title: "Hàn Quốc" },
  { path: "trung-quoc", title: "Trung Quốc" },
  { path: "nhat-ban", title: "Nhật Bản" },
  { path: "dai-loan", title: "Đài Loan" },
  { path: "hong-kong", title: "Hồng Kông" },
  { path: "an-do", title: "Ấn Độ" },
  { path: "philippines", title: "Philippines" },
  { path: "indonesia", title: "Indonesia" },
  { path: "singapore", title: "Singapore" },
  { path: "viet-nam", title: "Việt Nam" },
  { path: "thai-lan", title: "Thái Lan" },
  { path: "malaysia", title: "Malaysia" },
  { path: "my", title: "Mỹ" }, // United States
  { path: "canada", title: "Canada" },
  { path: "anh", title: "Anh" }, // United Kingdom
  { path: "phap", title: "Pháp" }, // France
  { path: "duc", title: "Đức" }, // Germany
  { path: "tay-ban-nha", title: "Tây Ban Nha" }, // Spain
  { path: "y", title: "Ý" }, // Italy
  { path: "brazil", title: "Brazil" },
  { path: "argentina", title: "Argentina" },
  { path: "chile", title: "Chile" },
  { path: "peru", title: "Peru" },
  { path: "colombia", title: "Colombia" },
  { path: "uruguay", title: "Uruguay" },
  { path: "venezuela", title: "Venezuela" },
  { path: "mexico", title: "Mexico" },
  { path: "australia", title: "Australia" },
  { path: "new-zealand", title: "New Zealand" },
  { path: "south-africa", title: "Nam Phi" }, // South Africa
  { path: "nigeria", title: "Nigeria" },
  { path: "kenya", title: "Kenya" },
  { path: "egypt", title: "Ai Cập" }, // Egypt
  { path: "morocco", title: "Morocco" },
  { path: "algeria", title: "Algeria" },
  { path: "tunis", title: "Tunisia" },
  { path: "saudi-arabia", title: "Ả Rập Xê Út" },
  { path: "jordan", title: "Jordan" },
  { path: "lebanon", title: "Lebanon" },
  { path: "israel", title: "Israel" },
  { path: "turkey", title: "Thổ Nhĩ Kỳ" },
  { path: "greece", title: "Hy Lạp" },
  { path: "cyprus", title: "Cyprus" },
  { path: "poland", title: "Ba Lan" },
  { path: "hungary", title: "Hungary" },
  { path: "czech-republic", title: "Cộng Hòa Séc" },
  { path: "romania", title: "Romania" },
  { path: "bulgaria", title: "Bulgaria" },
  { path: "serbia", title: "Serbia" },
  { path: "croatia", title: "Croatia" },
  { path: "slovenia", title: "Slovenia" },
  { path: "slovakia", title: "Slovakia" },
  { path: "ukraine", title: "Ukraine" },
  { path: "belarus", title: "Belarus" },
  { path: "lithuania", title: "Lithuania" },
  { path: "latvia", title: "Latvia" },
  { path: "estonia", title: "Estonia" },
  { path: "finland", title: "Phần Lan" },
  { path: "sweden", title: "Thụy Điển" },
  { path: "norway", title: "Na Uy" },
  { path: "denmark", title: "Đan Mạch" },
  { path: "iceland", title: "Iceland" },
  { path: "portugal", title: "Bồ Đào Nha" },
  { path: "switzerland", title: "Thụy Sĩ" },
  { path: "austria", title: "Áo" },
  { path: "liechtenstein", title: "Liechtenstein" },
  { path: "monaco", title: "Monaco" },
  { path: "luxembourg", title: "Luxembourg" },
  { path: "andorra", title: "Andorra" },
  { path: "san-marino", title: "San Marino" },
  { path: "vatican", title: "Vatican" },
  { path: "malta", title: "Malta" },
  { path: "georgia", title: "Georgia" },
  { path: "armenia", title: "Armenia" },
  { path: "azerbaijan", title: "Azerbaijan" },
  { path: "kazakhstan", title: "Kazakhstan" },
  { path: "uzbekistan", title: "Uzbekistan" },
  { path: "turkmenistan", title: "Turkmenistan" },
  { path: "kyrgyzstan", title: "Kyrgyzstan" },
  { path: "mongolia", title: "Mông Cổ" },
  { path: "bahrain", title: "Bahrain" },
  { path: "oman", title: "Oman" },
  { path: "qatar", title: "Qatar" },
  { path: "yemen", title: "Yemen" },
  { path: "sri-lanka", title: "Sri Lanka" },
  { path: "maldives", title: "Maldives" },
  { path: "nepal", title: "Nepal" },
  { path: "bhutan", title: "Bhutan" },
  { path: "pakistan", title: "Pakistan" },
  { path: "afghanistan", title: "Afghanistan" },
]
