export const PhoneNumberRegex = /^d{11}$/
export const pwdRegex = /^(?=.*[a-zA-Z])(?=.*\d).{6,}$/
export const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
export const VietnameseRegex = /^[^\u00C0-\u1EF9]+$/i
export const EmailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
export const checkNumberRegex = /^-?\d*\.?\d+$/
export const VNPhoneNumberRegex = /(84|0[3|5|7|8|9])+([0-9]{8})\b/g
export const checkSpaceRegex = /\s/
export const checkUPCRegex = /^[A-Z]+$/
