export const years = []
for (let year = 2024; year >= 1900; year--) {
  years.push(year.toString())
}
export const Arrange = ["Mặc Định", "Năm sản xuất", "Thời gian đăng", "Thời gian cập nhật"]
export const Format = ["Mặc định", "Phim bộ", "Phim hành động", "Phim lẻ", "Phim Chiếu rạp"]
export const Nationals = [
  "Tất Cả Quốc Gia",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Kyrgyzstan",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Việt Nam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
]
export const CategoryFilms = [
  "Tất Cả Thể Loại",
  "Hành Động",
  "Hài Hước",
  "Kinh Dị",
  "Tâm Lý",
  "Tình Cảm",
  "Hành Động - Phiêu Lưu",
  "Khoa Học Viễn Tưởng",
  "Viễn Tưởng",
  "Hình Sự",
  "Gia Đình",
  "Lịch Sử",
  "Hài Kịch",
  "Âm Nhạc",
  "Hoạt Hình",
  "Nhạc Kịch",
  "Thần Thoại",
  "Chính Kịch",
  "Cổ Trang",
  "Tài Liệu",
  "Thực Tế",
  "Lãng Mạn",
  "Bi Kịch",
  "Mạo Hiểm",
  "Tội Phạm",
  "Chiến Tranh",
  "Drama",
  "Fantasy", // Phim giả tưởng
  "Romance", // Phim lãng mạn
  "Documentary", // Phim tài liệu
  "Adventure", // Phim phiêu lưu
]
